repos:
#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.5.0
#    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
#    -   id: check-yaml
#    -   id: check-added-large-files

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        # isort will use the configuration from pyproject.toml

#-   repo: https://github.com/psf/black
#    rev: 23.10.1
#    hooks:
#    -   id: black
#        language_version: python3

#-   repo: https://github.com/pycqa/flake8
#    rev: 6.1.0
#    hooks:
#    -   id: flake8
#        additional_dependencies: [flake8-docstrings]
