version: '3.8'

services:
  agg-ai-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: agg-ai-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/agg-ai
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: agg-ai-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agg-ai
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: