version: '3.8'

services:
  agg-ai-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: agg-ai-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/agg-ai
      - OTEL_SERVICE_NAME=agg-ai-api
      - GOOGLE_CLIENT_ID=485345819112-cc79gm8kscqirc6e71bavk1vvat8ov53.apps.googleusercontent.com
      - JWT_SECRET_KEY=your_jwt_secret_key
      - JWT_EXPIRATION_MINUTES=86400
      - ANTHROPIC_API_KEY=test-key
      - OPENAI_API_KEY=test-key
      - STORAGE_EMULATOR_HOST=http://gcp-storage-emulator:4443
      - GCP_PROJECT_ID=dev-agg-ai
      - GCP_BUCKET_NAME=dev-agg-ai-resources
    depends_on:
      - db
      - jaeger
      - gcp-storage-emulator
    restart: unless-stopped
    networks:
      - agg-ai-network

  db:
    image: postgres:17
    container_name: agg-ai-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agg-ai
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - agg-ai-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC endpoint
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    networks:
      - agg-ai-network

  gcp-storage-emulator:
    image: oittaa/gcp-storage-emulator:latest
    container_name: gcp-storage-emulator
    ports:
      - "4443:8080"  # Storage API port
    volumes:
      - gcp_storage_data:/storage
    restart: unless-stopped
    networks:
      - agg-ai-network
    command: ["start", "--default-bucket=agg-ai-bucket"]

volumes:
  postgres_data:
  gcp_storage_data:

networks:
  agg-ai-network:
    driver: bridge