version: '3.8'

services:
  t4-chat-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: t4-chat-api
    ports:
      - "9001:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/t4-chat
      - OTEL_SERVICE_NAME=t4-chat-api
      - GOOGLE_CLIENT_ID=test-key
      - JWT_SECRET_KEY=your_jwt_secret_key
      - JWT_EXPIRATION_MINUTES=86400
      - ANTHROPIC_API_KEY=test-key
      - STORAGE_EMULATOR_HOST=http://gcp-storage-emulator:4443
      - GCP_PROJECT_ID=dev-t4-chat
      - GCP_BUCKET_NAME=dev-t4-chat-resources
      - MOCK_AI_RESPONSE=True
      - ADMIN_EMAILS=["stepun.tita@gmail.com","pxlxpenko@gmail.com","ostashko4@gmail.com","avdieiev.oleksii@gmail.com"]
      - API_KEY_ENCRYPTION_KEY=test-key
      - OPENAI_API_KEY=test-key
      - DEEPSEEK_API_KEY=test-key
      - GEMINI_API_KEY=test-key
      - XAI_API_KEY=test-key
      - GROQ_API_KEY=test-key
      - TOGETHERAI_API_KEY=test-key
      - LLAMA_API_KEY=test-key
      - OPENROUTER_API_KEY=test-key
    depends_on:
      - db
      - jaeger
      - gcp-storage-emulator
    restart: unless-stopped
    networks:
      - t4-chat-network

  db:
    image: postgres:17
    container_name: t4-chat-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=t4-chat
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - t4-chat-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC endpoint
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    networks:
      - t4-chat-network

  gcp-storage-emulator:
    image: oittaa/gcp-storage-emulator:latest
    container_name: gcp-storage-emulator
    ports:
      - "4443:8080"  # Storage API port
    volumes:
      - gcp_storage_data:/storage
    restart: unless-stopped
    networks:
      - t4-chat-network
    command: ["start", "--default-bucket=t4-chat-bucket"]

volumes:
  postgres_data:
  gcp_storage_data:

networks:
  t4-chat-network:
    driver: bridge