"""add_system_prompts

Revision ID: 9df1ec5535e4
Revises: 077376217cb6
Create Date: 2025-03-04 23:55:14.402363-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9df1ec5535e4'
down_revision: Union[str, None] = '077376217cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='agg_ai'
    )
    op.create_index(op.f('ix_agg_ai_prompts_id'), 'prompts', ['id'], unique=False, schema='agg_ai')
    op.add_column('ai_provider_models', sa.Column('prompt_id', sa.Integer(), nullable=True), schema='agg_ai')
    op.create_foreign_key(None, 'ai_provider_models', 'prompts', ['prompt_id'], ['id'], source_schema='agg_ai', referent_schema='agg_ai', ondelete='CASCADE')
    op.drop_column('ai_provider_models', 'modalities', schema='agg_ai')
    op.add_column('chat_messages', sa.Column('model_id', sa.Integer(), nullable=True), schema='agg_ai')
    op.create_foreign_key(None, 'chat_messages', 'ai_provider_models', ['model_id'], ['id'], source_schema='agg_ai', referent_schema='agg_ai', ondelete='SET NULL')
    op.drop_column('chat_messages', 'provider', schema='agg_ai')
    op.drop_column('chat_messages', 'model', schema='agg_ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True), schema='agg_ai')
    op.add_column('chat_messages', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True), schema='agg_ai')
    op.drop_constraint(None, 'chat_messages', schema='agg_ai', type_='foreignkey')
    op.drop_column('chat_messages', 'model_id', schema='agg_ai')
    op.add_column('ai_provider_models', sa.Column('modalities', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False), schema='agg_ai')
    op.drop_constraint(None, 'ai_provider_models', schema='agg_ai', type_='foreignkey')
    op.drop_column('ai_provider_models', 'prompt_id', schema='agg_ai')
    op.drop_index(op.f('ix_agg_ai_prompts_id'), table_name='prompts', schema='agg_ai')
    op.drop_table('prompts', schema='agg_ai')
    # ### end Alembic commands ###
