"""add_user_table

Revision ID: 077376217cb6
Revises: 67e7152224fb
Create Date: 2025-03-02 16:40:20.969838-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077376217cb6'
down_revision: Union[str, None] = '67e7152224fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='agg_ai'
    )
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], source_schema='agg_ai', referent_schema='agg_ai', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', schema='agg_ai', type_='foreignkey')
    op.drop_table('users', schema='agg_ai')
    # ### end Alembic commands ###
