"""previous_message_fk_selected

Revision ID: bb4ad4aa352a
Revises: e647aaf2cbc6
Create Date: 2025-05-25 18:17:54.697448-05:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bb4ad4aa352a'
down_revision: Union[str, None] = 'e647aaf2cbc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('previous_message_id', sa.UUID(), nullable=True), schema='agg_ai')
    op.add_column('chat_messages', sa.Column('selected', sa.Boolean(), nullable=False, server_default='false'), schema='agg_ai')
    op.create_foreign_key('chat_messages_previous_message_id_fkey', 'chat_messages', 'chat_messages', ['previous_message_id'], ['id'], source_schema='agg_ai', referent_schema='agg_ai', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_previous_message_id_fkey', 'chat_messages', schema='agg_ai', type_='foreignkey')
    op.drop_column('chat_messages', 'selected', schema='agg_ai')
    op.drop_column('chat_messages', 'previous_message_id', schema='agg_ai')
    # ### end Alembic commands ###
