"""init_migration

Revision ID: 23d185d65ee9
Revises: 
Create Date: 2025-02-22 19:58:10.368156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d185d65ee9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS ai_providers;')
    op.create_table('ai_providers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_providers'
    )
    op.create_index(op.f('ix_ai_providers_ai_providers_id'), 'ai_providers', ['id'], unique=False, schema='ai_providers')
    op.create_table('ai_provider_models',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.ai_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_providers'
    )
    op.create_index(op.f('ix_ai_providers_ai_provider_models_id'), 'ai_provider_models', ['id'], unique=False, schema='ai_providers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP SCHEMA IF EXISTS ai_providers CASCADE;')
    op.drop_index(op.f('ix_ai_providers_ai_provider_models_id'), table_name='ai_provider_models', schema='ai_providers')
    op.drop_table('ai_provider_models', schema='ai_providers')
    op.drop_index(op.f('ix_ai_providers_ai_providers_id'), table_name='ai_providers', schema='ai_providers')
    op.drop_table('ai_providers', schema='ai_providers')
    # ### end Alembic commands ###
