"""add_seq_num

Revision ID: 047bb84b74fc
Revises: bb4ad4aa352a
Create Date: 2025-05-29 22:58:34.090805-05:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '047bb84b74fc'
down_revision: Union[str, None] = 'bb4ad4aa352a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column as nullable first
    op.add_column('chat_messages', sa.Column('seq_num', sa.Integer(), nullable=True), schema='agg_ai')
    
    # Step 2: Populate seq_num for existing records
    # Use ROW_NUMBER() to assign sequence numbers based on created_at within each chat
    op.execute("""
        UPDATE agg_ai.chat_messages 
        SET seq_num = subquery.rn
        FROM (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY chat_id ORDER BY created_at, role DESC) as rn
            FROM agg_ai.chat_messages
        ) as subquery
        WHERE chat_messages.id = subquery.id
    """)
    
    # Step 3: Now make the column NOT NULL since all records have values
    op.alter_column('chat_messages', 'seq_num',
               existing_type=sa.Integer(),
               nullable=False,
               schema='agg_ai')
    
    op.alter_column('chat_messages', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'),
               schema='agg_ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               schema='agg_ai')
    op.drop_column('chat_messages', 'seq_num', schema='agg_ai')
    # ### end Alembic commands ###
